language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '12'
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: report-coverage
      node_js: "10"
      script: npm run report-coverage
    - stage: release
      if: branch = master AND type != pull_request
      node_js: "10"
      script: npm run deploy-docs && npm run semantic-release
